export const ADD_TO_CARD="ADD_TO_CARD";
export const CHANGE_MESSAGE="CHANGE_MESSAGE";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const UPDATE_CART="UPDATE_CART";
export const OPEN_SNACKBAR="OPEN_SNACKBAR";
export const OPEN_SNACKBAR_CLOSE = "OPEN_SNACKBAR_CLOSE";
export const ADD_CUSTOMER="ADD_CUSTOMER";
export const OPEN_DRAWER_RES="OPEN_DRAWER_RES";
export const CLOSE_DRAWER_RES="CLOSE_DRAWER_RES";
export const CLOSE_DRAWER_LOG="CLOSE_DRAWER_LOG";
export const OPEN_DRAWER_LOG="OPEN_DRAWER_LOG";
export const LOGIN="LOGIN"
export const ACTION_LOGOUT="ACTION_LOGOUT";
export const ACTION_LOGIN="ACTION_LOGIN";
export const PAY_PRODUCT="PAY_PRODUCT";
export const DELETE_ALL_CART="DELETE_ALL_CART";

