export const ADD_TO_CARD="ADD_TO_CARD";
export const CHANGE_MESSAGE="CHANGE_MESSAGE";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const UPDATE_CART="UPDATE_CART";
export const OPEN_SNACKBAR="OPEN_SNACKBAR";
export const OPEN_SNACKBAR_CLOSE = "OPEN_SNACKBAR_CLOSE"

